/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as BuilderIndexRouteImport } from './routes/builder.index'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as PlayAttemptIdRouteImport } from './routes/play.$attemptId'
import { Route as BuilderQuizIdRouteImport } from './routes/builder.$quizId'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRoute,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayAttemptIdRoute = PlayAttemptIdRouteImport.update({
  id: '/$attemptId',
  path: '/$attemptId',
  getParentRoute: () => PlayRoute,
} as any)
const BuilderQuizIdRoute = BuilderQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => BuilderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/builder/$quizId': typeof BuilderQuizIdRoute
  '/play/$attemptId': typeof PlayAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder/$quizId': typeof BuilderQuizIdRoute
  '/play/$attemptId': typeof PlayAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/builder': typeof BuilderIndexRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteWithChildren
  '/play': typeof PlayRouteWithChildren
  '/builder/$quizId': typeof BuilderQuizIdRoute
  '/play/$attemptId': typeof PlayAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/play'
    | '/builder/$quizId'
    | '/play/$attemptId'
    | '/results/$attemptId'
    | '/builder/'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder/$quizId'
    | '/play/$attemptId'
    | '/results/$attemptId'
    | '/builder'
    | '/play'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/play'
    | '/builder/$quizId'
    | '/play/$attemptId'
    | '/results/$attemptId'
    | '/builder/'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRouteWithChildren
  PlayRoute: typeof PlayRouteWithChildren
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRoute
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$attemptId': {
      id: '/play/$attemptId'
      path: '/$attemptId'
      fullPath: '/play/$attemptId'
      preLoaderRoute: typeof PlayAttemptIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/builder/$quizId': {
      id: '/builder/$quizId'
      path: '/$quizId'
      fullPath: '/builder/$quizId'
      preLoaderRoute: typeof BuilderQuizIdRouteImport
      parentRoute: typeof BuilderRoute
    }
  }
}

interface BuilderRouteChildren {
  BuilderQuizIdRoute: typeof BuilderQuizIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
}

const BuilderRouteChildren: BuilderRouteChildren = {
  BuilderQuizIdRoute: BuilderQuizIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
}

const BuilderRouteWithChildren =
  BuilderRoute._addFileChildren(BuilderRouteChildren)

interface PlayRouteChildren {
  PlayAttemptIdRoute: typeof PlayAttemptIdRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayAttemptIdRoute: PlayAttemptIdRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRouteWithChildren,
  PlayRoute: PlayRouteWithChildren,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
